DROP TABLE IF EXISTS Accounts;

CREATE TABLE IF NOT EXISTS 'Accounts' (
'ID'		   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
'Username'	   TEXT NOT NULL,
'Password'	   TEXT NOT NULL,
'Access'	   TEXT NOT NULL
);

SELECT ID, Username FROM Accounts WHERE Access = 'ADMIN';